# Setup
title:               Andrea & Josh
tagline:             ''
description:         ''
url:                 https://andreajosh.wedding
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andrea Lehn & Josh Bradshaw
  email:             wedding@andreajosh.wedding

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
